### ISSUE TITLE
criu restore hangs

### ISSUE THREAD

**Issue by avagin** [xemul/criu#13]
```
22075 ?        S      0:00      \_ bash -c ( mount --make-rprivate / && umount -l  /proc && mount -t proc proc /proc/ && bash -x test/jenkins/criu-iter.sh )
22076 ?        S      0:00          \_ bash -c ( mount --make-rprivate / && umount -l  /proc && mount -t proc proc /proc/ && bash -x test/jenkins/criu-iter.sh )
22080 ?        S      0:00              \_ bash -x test/jenkins/criu-iter.sh
26359 ?        S      0:00                  \_ make -C test ZDTM_ARGS=-C -i 3 -x maps04 zdtm
26410 ?        S      0:00                      \_ make -f Makefile.zdtm zdtm_nons
10149 ?        S      0:00                          \_ /bin/sh -c ./zdtm.sh --ct -C -i 3 -x maps04 -r transition/fork2 > transition_fork2.log 2>&1;  \ { ret=$?; fname=transitio
10150 ?        S      0:00                              \_ /bin/bash ./zdtm.sh --ct -C -i 3 -x maps04 -r transition/fork2
10163 ?        S      0:00                                  \_ ./zdtm_ct ./zdtm.sh -C -i 3 -x maps04 -r transition/fork2
10164 ?        Ss     0:00                                      \_ /bin/bash ./zdtm.sh -C -i 3 -x maps04 -r transition/fork2
10414 ?        Ss     0:00                                          \_ /var/lib/jenkins/jobs/CRIU-iter/workspace/criu restore -D /var/lib/jenkins/jobs/CRIU-iter/workspace/test/
10415 ?        Ss     0:00                                              \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10416 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10417 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10418 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10419 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10420 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10421 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10422 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10423 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10424 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10425 ?        S      0:00                                                  \_ ./fork2 --pidfile=fork2.pid --outfile=fork2.out
10426 ?        Z      0:00                                                  \_ [fork2] <defunct>
```
```
[root@jenkins workspace]# ./crit show /proc/10414/cwd/core-146.img 
{
    "magic": "CORE", 
    "entries": [
        {
            "mtype": "X86_64", 
            "tc": {
                "task_state": 2, 
                "exit_code": 0, 
                "personality": 0, 
                "flags": 0, 
                "blk_sigset": "0x0", 
                "comm": "fork2"
            }
        }
    ]
}
```
```
(gdb) bt
#0  __syscall_common () at arch/x86/syscalls/syscall-common-x86-64.S:15
#1  0x000000000041b596 in futex_wait_while_gt (v=0, f=0x7f905035c00c) at include/lock.h:92
#2  restore_wait_inprogress_tasks () at cr-restore.c:1594
#3  0x000000000041bd63 in restore_switch_stage (next_stage=5) at cr-restore.c:1614
#4  restore_root_task (init=<optimized out>) at cr-restore.c:1876
#5  0x00000000004301d9 in cr_restore_tasks () at cr-restore.c:1990
#6  0x000000000041e7b6 in main (argc=<optimized out>, argv=0x7ffdffe0c468, envp=<optimized out>) at crtools.c:589
(gdb) frame 2
#2  restore_wait_inprogress_tasks () at cr-restore.c:1594
1594		futex_wait_while_gt(np, 0);
(gdb) p *np
$1 = {raw = {counter = 1}}
```

**Comment by avagin** [comment]
```
(gdb) p *task_entries
$2 = {nr_threads = 12, nr_tasks = 12, nr_helpers = 0, nr_in_progress = {raw = {counter = 1}}, start = {raw = {counter = 5}}, cr_err = {counter = 0}, userns_sync_lock = {
    raw = {counter = 0}}}
```

**Comment by avagin** [comment]
Fixed by https://github.com/xemul/criu/commit/f13ec96e58688614f732422e67ed34231b58e2ba
