### ISSUE TITLE
crit: netdev-9.img decode fails

### ISSUE THREAD

**Issue by avagin** [xemul/criu#161]
https://ci.openvz.org/job/CRIU/job/CRIU-crit/branch/criu-dev/282/console
```
=== Run 251/251 ================
test/dump/zdtm/static/netns-dev/31/1/netdev-9.img decode fails
test/dump/zdtm/static/netns-dev/31/1/netdev-9.img pretty decode fails
FAIL
```

```
[root@usr-LAN-dhcp-38 criu-dev]# ./crit/crit decode -i test/dump/zdtm/static/netns-dev/31/1/netdev-9.img 
Traceback (most recent call last):
  File "./crit/crit", line 275, in <module>
    main()
  File "./crit/crit", line 272, in main
    opts["func"](opts)
  File "./crit/crit", line 28, in decode
    img = pycriu.images.load(inf(opts), opts['pretty'])
  File "/var/lib/jenkins/workspace/CRIU/CRIU-crit/criu-dev/crit/pycriu/images/images.py", line 426, in load
    image['entries'] = handler.load(f, pretty)
  File "/var/lib/jenkins/workspace/CRIU/CRIU-crit/criu-dev/crit/pycriu/images/images.py", line 99, in load
    pb.ParseFromString(f.read(size))
  File "/usr/lib/python2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 841, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 633, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 520, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 487, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 42: 'utf8' codec can't decode byte 0x94 in position 42: invalid start byte in field: sysctl_entry.sarg
```

**Comment by avagin** [comment]
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 42: 'utf8' codec can't decode byte 0x94 in position 42: invalid start byte in field: sysctl_entry.sargi '2607:f0d0:1002:0051:0000:0000:0000:0004\n`\x7f\x94'
```

**Comment by avagin** [comment]
The following patch helps. @Snorch, could you look at this issue?
```
diff --git a/criu/net.c b/criu/net.c
index 59c1161..36619af 100644
--- a/criu/net.c
+++ b/criu/net.c
@@ -330,7 +330,7 @@ static int dump_one_netdev(int type, struct ifinfomsg *ifi,
        int size4 = ARRAY_SIZE(devconfs4);
        SysctlEntry *confs6 = NULL;
        int size6 = ARRAY_SIZE(devconfs6);
-       char stable_secret[MAX_STR_CONF_LEN + 1];
+       char stable_secret[MAX_STR_CONF_LEN + 1] = "";
 
        if (!tb[IFLA_IFNAME]) {
                pr_err("No name for link %d\n", ifi->ifi_index);
@@ -1131,8 +1131,8 @@ static int dump_netns_conf(struct cr_imgset *fds)
        int size4 = ARRAY_SIZE(devconfs4);
        SysctlEntry *def_confs6 = NULL, *all_confs6 = NULL;
        int size6 = ARRAY_SIZE(devconfs6);
-       char def_stable_secret[MAX_STR_CONF_LEN + 1];
-       char all_stable_secret[MAX_STR_CONF_LEN + 1];
+       char def_stable_secret[MAX_STR_CONF_LEN + 1] = "";
+       char all_stable_secret[MAX_STR_CONF_LEN + 1] = "";
 
        netns.n_def_conf4 = size4;
        netns.n_all_conf4 = size4;
```

**Comment by Snorch** [comment]
Sting field sysctl_entry.sarg has wrong length in protobuf encoding in netdev-9 image, according to https://developers.google.com/protocol-buffers/docs/encoding :

In netdev-9.img binary representation of sarg field is: "1a 2c 32 36 30 37 3a 66 30 64 30 3a 31 30 30 32 3a 30 30 35 31 3a 30 30 30 30 3a 30 30 30 30 3a 30 30 30 30 3a 30 30 30 34 0a c0 f4 a7 01"
Field key is 0x1a - means type 2(Length-delimited field), field 3 - that is sarg field.
Field len is 0x2c which is 44, first 40-byte "2607:f0d0:1002:0051:0000:0000:0000:0004\0" and then last 4 - "c0 f4 a7 01" where 0xc0 is not Unicode.

In sysctl_op we just read() from sysctl so no '\0' is added in the end of the string. So your patch zero-initializing arrays will fix the problem.
Acked-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

May be we also need to add '\0' in sysctl_read_char?

diff --git a/criu/sysctl.c b/criu/sysctl.c
index 77d9bda..58fe5c3 100644
--- a/criu/sysctl.c
+++ b/criu/sysctl.c
@@ -136,6 +136,7 @@ sysctl_read_char(int fd, struct sysctl_req *req, char *arg, int nr)
                        pr_perror("Can't read %s", req->name);
                goto err;
        }
+       arg[ret]='\0';
        ret = 0;
 
 err:
