### ISSUE TITLE
zdtm/static/sigpending FAIL at CRIU pre-dump 

### ISSUE THREAD

**Issue by avagin** [xemul/criu#189]
```
[root@fc22-vm criu]# python test/zdtm.py run -t zdtm/static/sigpending --pre 2 --dedup
=== Run 1/1 ================

======================= Run zdtm/static/sigpending in h ========================
Start test
./sigpending --pidfile=sigpending.pid --outfile=sigpending.out
Run criu pre-dump
############## Test zdtm/static/sigpending FAIL at CRIU pre-dump ###############
Wait for zdtm/static/sigpending to die for 0.100000
##################################### FAIL #####################################
```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000435744 in cr_pre_dump_finish (ret=0) at cr-dump.c:1452
1452			pr_info("\tPre-dumping %d\n", ctl->pid.virt);
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.23.1-8.fc24.x86_64 libnl3-3.2.27-3.fc24.x86_64 libselinux-2.5-3.fc24.x86_64 pcre-8.39-2.fc24.x86_64 protobuf-c-1.2.1-1.fc24.x86_64
(gdb) bt
#0  0x0000000000435744 in cr_pre_dump_finish (ret=0) at cr-dump.c:1452
#1  cr_pre_dump_tasks (pid=pid@entry=24) at cr-dump.c:1556
#2  0x000000000041f665 in main (argc=<optimized out>, argv=0x7ffda430e818, envp=<optimized out>) at crtools.c:753
```

**Comment by avagin** [comment]
Subject: [PATCH] pre-dump: skip dead tasks

**Comment by xemul** [comment]
Which branch?

**Comment by avagin** [comment]
@xemul  criu-dev
