### ISSUE TITLE
A test is segfaulted after dump/restore

### ISSUE THREAD

**Issue by avagin** [xemul/criu#207]
https://travis-ci.org/avagin/criu/jobs/153825188

Cc: @0x7f454c46

**Comment by avagin** [comment]
https://travis-ci.org/avagin/criu/jobs/153736917
```
+ ps -p 15100
  PID TTY          TIME CMD
15100 ?        00:00:00 link10
+ cat /proc/15100/status
Name:	link10
State:	S (sleeping)
Tgid:	15100
Ngid:	0
Pid:	15100
PPid:	14781
TracerPid:	0
Uid:	100000	100000	100000	100000
Gid:	400000	400000	400000	400000
FDSize:	32768
Groups:	
VmPeak:	   22796 kB
VmSize:	    4492 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    4104 kB
VmRSS:	      96 kB
VmData:	     192 kB
VmStk:	     284 kB
VmExe:	      20 kB
VmLib:	    1908 kB
VmPTE:	      36 kB
VmSwap:	       0 kB
Threads:	1
SigQ:	0/29846
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000001001000
SigCgt:	0000000000014000
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
Seccomp:	0
Cpus_allowed:	3
Cpus_allowed_list:	0-1
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	31
nonvoluntary_ctxt_switches:	1
+ ls -l /proc/15100/fd
total 0
lrwx------ 1 100000 400000 64 Aug 20 05:36 0 -> /dev/null
l-wx------ 1 100000 400000 64 Aug 20 05:36 1 -> /zdtm/static/link10.outns
l-wx------ 1 100000 400000 64 Aug 20 05:36 2 -> /zdtm/static/link10.outns
+ cat /proc/15100/maps
00400000-00405000 r-xp 00000000 08:01 265100                             /zdtm/static/link10
00605000-00606000 r--p 00005000 08:01 265100                             /zdtm/static/link10
00606000-00607000 rw-p 00006000 08:01 265100                             /zdtm/static/link10
015fb000-0161c000 rw-p 00000000 00:00 0                                  [heap]
2b2d055e2000-2b2d05605000 r-xp 00000000 08:01 265362                     /lib64/ld-linux-x86-64.so.2
2b2d05605000-2b2d05607000 r--p 00000000 00:00 0                          [vvar]
2b2d05607000-2b2d05609000 r-xp 00000000 00:00 0                          [vdso]
2b2d05609000-2b2d0560e000 rw-p 00000000 00:00 0 
2b2d05804000-2b2d05805000 r--p 00022000 08:01 265362                     /lib64/ld-linux-x86-64.so.2
2b2d05805000-2b2d05806000 rw-p 00023000 08:01 265362                     /lib64/ld-linux-x86-64.so.2
2b2d05806000-2b2d05807000 rw-p 00000000 00:00 0 
2b2d05807000-2b2d059c1000 r-xp 00000000 08:01 265390                     /lib/x86_64-linux-gnu/libc.so.6
2b2d059c1000-2b2d05bc1000 ---p 001ba000 08:01 265390                     /lib/x86_64-linux-gnu/libc.so.6
2b2d05bc1000-2b2d05bc5000 r--p 001ba000 08:01 265390                     /lib/x86_64-linux-gnu/libc.so.6
2b2d05bc5000-2b2d05bc7000 rw-p 001be000 08:01 265390                     /lib/x86_64-linux-gnu/libc.so.6
2b2d05bc7000-2b2d05bcc000 rw-p 00000000 00:00 0 
7ffdec93d000-7ffdec983000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
+ exec
+ cat
+ echo 'bt
i r
disassemble $rip-0x10,$rip + 0x10
'
+ gdb -c /tmp/zdtm-core-15100-link10.core /proc/self/fd/33
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /proc/self/fd/33...done.
warning: core file may not match specified executable file.
[New LWP 1]
warning: Corrupted shared library list: 0x2b2d05806760 != 0x0
Core was generated by `./link10 --pidfile=link10.pid --outfile=link10.out --filename=link10.test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002b2d055ebf4e in ?? ()
(gdb) #0  0x00002b2d055ebf4e in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) rax            0x0	0
rbx            0xa4f92301	2767790849
rcx            0x400320	4195104
rdx            0x7ffdec93f220	140728572572192
rsi            0xa4f92301	2767790849
rdi            0x400aef	4197103
rbp            0x0	0x0
rsp            0x7ffdec93f0e0	0x7ffdec93f0e0
r8             0x293e48c	43246732
r9             0x7ffdec93f120	140728572571936
r10            0x2b2d05806520	47472365823264
r11            0x7ffdec93f220	140728572572192
r12            0x3	3
r13            0x2b2d0560a9c8	47472363743688
r14            0x0	0
r15            0x1	1
rip            0x2b2d055ebf4e	0x2b2d055ebf4e
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x6b	107
```

**Comment by 0x7f454c46** [comment]
> (gdb) #0  0x00002b2d055ebf4e in ?? ()
> #1  0x0000000000000000 in ?? ()

It's in ld-linux-x86-64.so.2:

> 2b2d055e2000-2b2d05605000 r-xp 00000000 08:01 265362                     /lib64/ld-linux-x86-64.so.2

hex(0x2b2d055ebf4e - 0x2b2d055e2000) = '0x9f4e'
Armed with objdump on travis:
https://travis-ci.org/0x7f454c46/criu/builds/153857235

>  
   9f45:	48 c7 44 24 40 00 00     movq   $0x0,0x40(%rsp)
>     9f4c:	00 00 
**9f4e:	48 8b 78 28            mov    0x28(%rax),%rdi**
>     9f52:	4c 39 f7             	cmp    %r14,%rdi
>     9f55:	48 89 7c 24 50       	mov    %rdi,0x50(%rsp)
>     9f5a:	0f 84 f0 00 00 00    	je     a050 <_dl_rtld_di_serinfo+0x970>
>     9f60:	f6 44 24 7c 02       	testb  $0x2,0x7c(%rsp)

Just at the beggining of some function, hmm

**Comment by 0x7f454c46** [comment]
> (gdb) rax            0x0    0

Obivious, what happend, the question, why?

**Comment by cyrillos** [comment]
This is inside _dl_rtld_di_serinfo function. Googling didn't reveal any similar problem worldwide.

**Comment by cyrillos** [comment]
This function is called from dlinfo helper

**Comment by avagin** [comment]
```     sigaltstack-30675 [001] d...   786.597408: signal_deliver: sig=15 errno=0 code=0 sa_handler=403590 sa_flags=14000000^M
     sigaltstack-30675 [001] d...   786.597410: page_fault_kernel: address=0x7ffd9d1b7240 ip=__clear_user error_code=0x3^M
     sigaltstack-30675 [001] d...   786.597412: page_fault_kernel: address=0x7ffd9d1b6e80 ip=handle_signal error_code=0x3^M
     sigaltstack-30675 [001] d...   786.597414: page_fault_user: address=0x403590 ip=0x403590 error_code=0x14^M
     sigaltstack-30675 [001] d...   786.597418: page_fault_user: address=0x2b842b611068 ip=0x40359f error_code=0x4^M
     sigaltstack-30675 [001] d...   786.597420: page_fault_user: address=0x2b842b81b320 ip=0x2b842b81b320 error_code=0x14^M
     sigaltstack-30675 [001] d...   786.597433: page_fault_user: address=0x2b842b610fa0 ip=0x2b842bb1e71b error_code=0x6^M
     sigaltstack-30675 [001] d...   786.597437: page_fault_user: address=0x2b842b5fd4a0 ip=0x2b842b5fd4a0 error_code=0x14^M
     sigaltstack-30675 [001] d...   786.597442: page_fault_user: address=0x2b842b60ff68 ip=0x2b842b5f64c6 error_code=0x4^M
     sigaltstack-30675 [001] d...   786.597443: page_fault_user: address=0x2b842b61108c ip=0x2b842b5f64ef error_code=0x7^M
     sigaltstack-30675 [001] d...   786.597445: page_fault_user: address=0x2b842b80a9d8 ip=0x2b842b5f189f error_code=0x7^M
     sigaltstack-30675 [001] d...   786.597447: page_fault_user: address=0x28 ip=0x2b842b5f0f4e error_code=0x4^M
     sigaltstack-30675 [001] d...   786.597457: signal_generate: sig=11 errno=0 code=196609 comm=sigaltstack pid=30675 grp=0 res=0^M
     sigaltstack-30675 [001] d...   786.597458: signal_deliver: sig=11 errno=0 code=196609 sa_handler=0 sa_flags=0^M
```
```
Core was generated by `./sigaltstack --pidfile=sigaltstack.pid --outfile=sigaltstack.out'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002b842b5f0f4e in ?? ()
(gdb) #0  0x00002b842b5f0f4e in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) rax            0x0	0
rbx            0xa4f92301	2767790849
rcx            0x400338	4195128
rdx            0x7ffd9d1b7300	140727239275264
rsi            0xa4f92301	2767790849
rdi            0x400b3c	4197180
rbp            0x0	0x0
rsp            0x7ffd9d1b71c0	0x7ffd9d1b71c0
r8             0x293e48c	43246732
r9             0x7ffd9d1b7200	140727239275008
r10            0x2b842b80b520	47846665532704
r11            0x7ffd9d1b7300	140727239275264
r12            0x4	4
r13            0x2b842b60fef8	47846663454456
r14            0x0	0
r15            0x1	1
rip            0x2b842b5f0f4e	0x2b842b5f0f4e
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x6b	107
(gdb) Dump of assembler code from 0x2b842b5f0f3e to 0x2b842b5f0f5e:
   0x00002b842b5f0f3e:	Cannot access memory at address 0x2b842b5f0f3e
(gdb) 
Dump of assembler code from 0x2b842b5f0f3e to 0x2b842b5f0f5e:
   0x00002b842b5f0f3e:	Cannot access memory at address 0x2b842b5f0f3e
(gdb) quit
```

**Comment by avagin** [comment]
gs and fctrl have different values before and after dump/restore
```
-syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
+0x00002b2009304709 in ?? ()
 (gdb) rax            0xfffffffffffffe00	-512
 rbx            0x7ffd123b1010	140724909314064
 rcx            0xffffffffffffffff	-1
@@ -39,14 +36,14 @@ r12            0x401f01	4202241
 r13            0x7ffd123f2de8	140724909583848
 r14            0x0	0
 r15            0x0	0
-rip            0x2b2009304709	0x2b2009304709 <syscall+25>
+rip            0x2b2009304709	0x2b2009304709
 eflags         0x206	[ PF IF ]
 cs             0x33	51
 ss             0x2b	43
 ds             0x0	0
 es             0x0	0
 fs             0x0	0
-gs             0x0	0
+gs             0x6b	107
 st0            0	(raw 0x00000000000000000000)
 st1            0	(raw 0x00000000000000000000)
 st2            0	(raw 0x00000000000000000000)
@@ -55,7 +52,7 @@ st4            0	(raw 0x0000000000000000
 st5            0	(raw 0x00000000000000000000)
 st6            0	(raw 0x00000000000000000000)
 st7            0	(raw 0x00000000000000000000)
-fctrl          0x0	0
+fctrl          0x40	64
```

**Comment by cyrillos** [comment]
gs=0x6b is definitely a reason for #gp signal. NULL segment selectors can be loaded in protected mode which are values from 0 to 3. Moreover the kernel operates with fs/gs base msr registers to handle gs/fs based instructions. So the main questions where such weird gs value came from... Continue investigating.

**Comment by 0x7f454c46** [comment]
Added dumping of %gs, it's somewhere here:

> (00.478568)      5: Error (criu/cr-restore.c:3165): sigreturn_restore: %gs value: 0
> pie: 5: Error (criu/pie/restorer.c:1147): gs value: 0x0
> (00.479754)      6: Error (criu/cr-restore.c:3165): sigreturn_restore: %gs value: 0
> pie: 6: Error (criu/pie/restorer.c:1147): gs value: 0x0
> (00.480801)      1: Error (criu/cr-restore.c:3165): sigreturn_restore: %gs value: 0
> pie: 1: Error (criu/pie/restorer.c:1147): gs value: 0x0
> pie: 1: Error (criu/pie/restorer.c:1493): gs value: 0x6b
> pie: 5: Error (criu/pie/restorer.c:1493): gs value: 0x6b
> pie: 6: Error (criu/pie/restorer.c:1493): gs value: 0x6b

**Comment by cyrillos** [comment]
OK, indeed the selector is setup by kernel from msr upon zero write. IOW, the issue is somewhere else.

**Comment by avagin** [comment]
Before dump:
```
(gdb) x/10 0x00002b8008625000
0x2b8008625000:	140660816	11136	140617382	11136
0x2b8008625010:	0	0	140614080	11136
0x2b8008625020:	22	0
```
After restore:
```
(gdb) x/10 0x00002b8008625000
0x2b8008625000:	0	0	0	0
0x2b8008625010:	0	0	0	0
0x2b8008625020:	0	0
```
```
root@ubuntu-2gb-nyc3-01:~/tmp3/criu# ./crit/crit show test/dump/zdtm/static/console/26/1/mm-26.img | grep -A 4 2b8008625000
                    "end": "0x2b8008625000", 
                    "pgoff": 0, 
                    "shmid": 0, 
                    "prot": "PROT_READ | PROT_EXEC", 
                    "flags": "MAP_PRIVATE | MAP_ANON", 
```
```
(00.007457) Pagemap generated: 2 pages (0 lazy) 0 holes 0 zeros
(00.007459) vaddr 2b8008625000
(00.007461) pme 80000000000000
(00.007462) vaddr 2b8008626000
(00.007464) pme 8000000000000
```

**Comment by avagin** [comment]
```
2b6944c21000-2b6944c23000 rw-p 00000000 00:00 0 ^M
Size:                  8 kB^M
Rss:                   8 kB^M
```
```
(gdb) x/10 0x00002b6944c21000
0x2b6944c21000:	1153568848	11113	1153525414	11113
0x2b6944c21010:	0	0	1153522112	11113
0x2b6944c21020:	22	0
```
```
(gdb) x/10 0x00002b6944c21000
0x2b6944c21000:	0	0	0	0
0x2b6944c21010:	0	0	0	0
0x2b6944c21020:	0	0
```
```
(00.006599) vaddr 2b6944c21000
(00.006601) pme 80000000000000
(00.006602) vaddr 2b6944c22000
(00.006604) pme 80000000000000
(00.006606) Pagemap generated: 0 pages (0 lazy) 0 holes 0 zeros
```

**Comment by avagin** [comment]
/proc/pid/pagemap doesn't work properly in this kernel. We can read values for a few pages or we can read a value for each page. A value for each page has to be the same in both cases, but here it is not.
```
root@ubuntu-2gb-nyc3-01:~/criu# cat ~/test_pagemap.py 
import sys, os

start	= eval(sys.argv[1])
end	= eval(sys.argv[2])

fd = os.open(sys.argv[3], os.O_RDONLY)

os.lseek(fd, start / 4096 * 8, os.SEEK_SET)
pfn = os.read(fd, (end - start) / 4096 * 8)

os.lseek(fd, start / 4096 * 8, os.SEEK_SET)

for i in xrange((end - start) / 4096):
	p = os.read(fd, 8)
	if pfn[i * 8 :i * 8 + 8] != p:
		print "%016x %r %r" % (start + i * 4096, pfn[i:i + 8], p)
root@ubuntu-2gb-nyc3-01:~/criu# python ~/test_pagemap.py 0x7ffe299ff000 0x7ffe29b9e000  /proc/1/pagemap 
00007ffe29b9a000 '\x00\x00\x00\x00\x00\x00\x00\x00' '\x00\x00\x00\x00\x00\x00\x80\x00'
00007ffe29b9b000 '\x00\x00\x00\x00\x00\x00\x00\x00' '\x00\x00\x00\x00\x00\x00\x80\x00'
```

**Comment by avagin** [comment]
It is a kernel bug. @tych0, could you help with this issue?

The kernel version:
Linux ubuntu-2gb-nyc3-01 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

The reproducer:
```
root@ubuntu-2gb-nyc3-01:~# cat test_pagemap_vdso.py 
import sys, os

fd = open("/proc/self/maps")
for l in fd:
	if "vdso"  in l:
		break

start, end = l.split()[0].split("-")
start = eval("0x" + start)
start = start -  4096
end = eval("0x" + end)
end = end + 4096

fd = os.open("/proc/self/pagemap", os.O_RDONLY)

os.lseek(fd, start / 4096 * 8, os.SEEK_SET)
pfn = os.read(fd, (end - start) / 4096 * 8)

os.lseek(fd, start / 4096 * 8, os.SEEK_SET)

for i in xrange((end - start) / 4096):
	p = os.read(fd, 8)
	if pfn[i * 8 :i * 8 + 8] != p:
		print "FAIL: %016x %r %r" % (start + i * 4096, pfn[i:i + 8], p)
		sys.exit(1)
print "PASS"
root@ubuntu-2gb-nyc3-01:~# python test_pagemap_vdso.py
FAIL: 00007ffe36364000 '\x00\x00\x00\x00\x00\x80\x00\x00' '\x05\xec\x07\x00\x00\x00\x80\xa0'
root@ubuntu-2gb-nyc3-01:~# uname -a
Linux ubuntu-2gb-nyc3-01 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
