### ISSUE TITLE
maps008 deadlocked

### ISSUE THREAD

**Issue by avagin** [xemul/criu#221]
```
 1980 ?        Ss     0:00  \_ sshd: root [priv]
 2006 ?        S      0:07  |   \_ sshd: root@notty
 2073 ?        Ss     0:00  |       \_ bash -c cd "/var/lib/jenkins" && java  -jar slave.jar
 2084 ?        Sl    19:04  |           \_ java -jar slave.jar
10029 ?        S      0:00  |               \_ /bin/sh -xe /tmp/hudson6968932645334978615.sh
10031 ?        S      0:00  |                   \_ /bin/sh ./test/jenkins/run_ct test/jenkins/criu.sh
10035 ?        S      0:00  |                       \_ unshare --mount --pid --fork -- /var/lib/jenkins/workspace/CRIU/CRIU-ppc64le/master/test/jenkins/_run_c
10036 ?        S      0:00  |                           \_ /bin/sh /var/lib/jenkins/workspace/CRIU/CRIU-ppc64le/master/test/jenkins/_run_ct test/jenkins/criu.
15545 ?        S      0:01  |                               \_ python2 ./test/zdtm.py run --all --keep-going --report report --parallel 4
27838 ?        S      0:00  |                                   \_ ./zdtm_ct zdtm.py
27848 ?        S      0:00  |                                       \_ python2 zdtm.py
27871 ?        S      0:00  |                                           \_ python2 zdtm.py
27899 ?        S      0:00  |                                               \_ make --no-print-directory -C zdtm/transition maps008.pid
27923 ?        S      0:00  |                                                   \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
27931 ?        Ss     0:00  |                                                       \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
27969 ?        R     75:32  |                                                           \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
27970 ?        R     75:33  |                                                           |   \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
28003 ?        R     75:33  |                                                           |   \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
28033 ?        R     75:33  |                                                           \_ ./maps008 --pidfile=maps008.pid --outfile=maps008.out
28060 ?        Z      0:00  |                                                           \_ [maps008] <defunct>

[root@criu ~]# gdb -p 27931
(gdb) bt
#0  0x00003fffb51a38e0 in __read_nocancel () from target:/lib64/libc.so.6
#1  0x000000001000514c in task_waiter_wait4 (t=0x3fffd52d2040, lockid=<optimized out>) at lock.c:44
#2  0x0000000010002888 in fork_and_setup (pfunc=0x10002d80 <proc13_func>) at maps008.c:46
#3  0x0000000010001e4c in proc1_func () at maps008.c:413
#4  main (argc=<optimized out>, argv=<optimized out>) at maps008.c:502

```

Cc: @eabatalov

**Comment by eabatalov** [comment]
Hello.

The version of maps008 source used in this test run is a little bit stale.
This version doesn't include "test: fix bug with huge PAGE_SIZE in transition/maps008" patch made specially for PPC arch. As I see from test cmd "/var/lib/jenkins/workspace/CRIU/CRIU-ppc64le/master/test/jenkins/_run_ct test/jenkins/criu." this run is performed on ppc.

So if I am right about PPC arch then this bug can be marked as invalid.
Need another reproduction with "test: fix bug with huge PAGE_SIZE in transition/maps008" patch applied.

**Comment by xemul** [comment]
Patch is 44c4ef842db926e74cf77781656f2a644c92025e
Have we seen this since then?

**Comment by eabatalov** [comment]
@xemul 
No bugs with maps008 now. Looks like this can be closed.
