### ISSUE TITLE
Core was generated by `../criu/criu swrk 4'.

### ISSUE THREAD

**Issue by xemul** [xemul/criu#254]
https://travis-ci.org/criupatchwork/criu/builds/180485406

Core was generated by `../criu/criu swrk 4'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000423213 in usernsd (sk=5) at criu/namespaces.c:1215
1215			BUG_ON(fd < 0 && flags & UNS_FDOUT);
(gdb) #0  0x0000000000423213 in usernsd (sk=5) at criu/namespaces.c:1215
#1  0x000000000047807c in start_usernsd () at criu/namespaces.c:1385
#2  0x000000000047aac1 in prepare_namespace_before_tasks ()
    at criu/namespaces.c:1684
#3  0x000000000042284c in restore_root_task (init=0x2b1e55d8a458)
    at criu/cr-restore.c:1796
#4  0x000000000044c934 in cr_restore_tasks () at criu/cr-restore.c:2095
#5  0x0000000000450a1d in restore_using_req (sk=sk@entry=4, 
    req=<optimized out>) at criu/cr-service.c:565
#6  0x0000000000450dd4 in cr_service_work (sk=4) at criu/cr-service.c:934
#7  0x000000000042465d in main (argc=3, argv=0x7ffdb197ab18, 
    envp=<optimized out>) at criu/crtools.c:320

**Comment by xemul** [comment]
Oops, already seen this in #245
