### ISSUE TITLE
__malloc_assert in show_ps () at ns.c:241

### ISSUE THREAD

**Issue by avagin** [xemul/criu#272]
```
Program terminated with signal SIGABRT, Aborted.
#0  0x00002ac3fcfe7c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) #0  0x00002ac3fcfe7c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002ac3fcfeb028 in __GI_abort () at abort.c:89
#2  0x00002ac3fd02e6ed in __malloc_assert (
    assertion=assertion@entry=0x2ac3fd132be8 "(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offs"..., file=file@entry=0x2ac3fd12e768 "malloc.c", 
    line=line@entry=2372, 
    function=function@entry=0x2ac3fd12eae6 <__func__.11321> "sysmalloc")
    at malloc.c:293
#3  0x00002ac3fd031b58 in sysmalloc (av=0x2ac3fd36f760 <main_arena>, nb=288)
    at malloc.c:2369
#4  _int_malloc (av=0x2ac3fd36f760 <main_arena>, bytes=272) at malloc.c:3800
#5  0x00002ac3fd0336c0 in __GI___libc_malloc (bytes=272) at malloc.c:2891
#6  0x00002ac3fcd9f23c in _dl_update_slotinfo (req_modid=1) at dl-tls.c:634
#7  0x00002ac3fcd8d21d in update_get_addr (ti=0x2ac3fd36ed90) at dl-tls.c:753
#8  0x00002ac3fcfed7c0 in __GI___call_tls_dtors ()
    at cxa_thread_atexit_impl.c:83
#9  0x00002ac3fcfed0e7 in __run_exit_handlers (status=status@entry=1, 
    listp=0x2ac3fd36f6c8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:40
#10 0x00002ac3fcfed1f5 in __GI_exit (status=status@entry=1) at exit.c:104
#11 0x0000000000402d54 in show_ps () at ns.c:241
#12 0x0000000000403659 in ns_init (argc=argc@entry=4, 
    argv=argv@entry=0x7ffcba69cac8) at ns.c:326
#13 0x000000000040274f in test_init (argc=4, argv=0x7ffcba69cac8)
    at test.c:160
#14 0x0000000000000000 in ?? ()
(gdb) rax            0x0	0
rbx            0x2ac3fd36f760	47021255227232
rcx            0x2ac3fcfe7c37	47021251525687
rdx            0x6	6
rsi            0x6	6
rdi            0x6	6
rbp            0x120	0x120
rsp            0x7ffcba65c408	0x7ffcba65c408
r8             0x2ac3fcdb1900	47021249206528
r9             0x2064656e6769736e	2334102031740531566
r10            0x8	8
r11            0x206	518
r12            0x0	0
r13            0x833020	8597536
r14            0x2ac3fd36f7b8	47021255227320
r15            0x833020	8597536
rip            0x2ac3fcfe7c37	0x2ac3fcfe7c37 <__GI_raise+55>
eflags         0x206	[ PF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) Dump of assembler code from 0x2ac3fcfe7c27 to 0x2ac3fcfe7c47:
   0x00002ac3fcfe7c27 <__GI_raise+39>:	movslq %edi,%rdx
   0x00002ac3fcfe7c2a <__GI_raise+42>:	movslq %esi,%rsi
   0x00002ac3fcfe7c2d <__GI_raise+45>:	movslq %ecx,%rdi
   0x00002ac3fcfe7c30 <__GI_raise+48>:	mov    $0xea,%eax
   0x00002ac3fcfe7c35 <__GI_raise+53>:	syscall 
=> 0x00002ac3fcfe7c37 <__GI_raise+55>:	cmp    $0xfffffffffffff000,%rax
   0x00002ac3fcfe7c3d <__GI_raise+61>:	ja     0x2ac3fcfe7c5d <__GI_raise+93>
   0x00002ac3fcfe7c3f <__GI_raise+63>:	repz retq 
   0x00002ac3fcfe7c41 <__GI_raise+65>:	nopl   0x0(%rax)
End of assembler dump.
(gdb) Dump of assembler code from 0x2ac3fcfe7c27 to 0x2ac3fcfe7c47:
   0x00002ac3fcfe7c27 <__GI_raise+39>:	movslq %edi,%rdx
   0x00002ac3fcfe7c2a <__GI_raise+42>:	movslq %esi,%rsi
   0x00002ac3fcfe7c2d <__GI_raise+45>:	movslq %ecx,%rdi
   0x00002ac3fcfe7c30 <__GI_raise+48>:	mov    $0xea,%eax
   0x00002ac3fcfe7c35 <__GI_raise+53>:	syscall 
=> 0x00002ac3fcfe7c37 <__GI_raise+55>:	cmp    $0xfffffffffffff000,%rax
   0x00002ac3fcfe7c3d <__GI_raise+61>:	ja     0x2ac3fcfe7c5d <__GI_raise+93>
   0x00002ac3fcfe7c3f <__GI_raise+63>:	repz retq 
   0x00002ac3fcfe7c41 <__GI_raise+65>:	nopl   0x0(%rax)
End of assembler dump.
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/193235182/log.txt
https://travis-ci.org/avagin/criu/jobs/193235182

**Comment by avagin** [comment]
Cc: @rppt @adrianreber

**Comment by avagin** [comment]
https://patchwork.criu.org/series/1078/

only four patches from this series was applied. It may be a reason of this fail.

**Comment by avagin** [comment]
Here is results with all patches https://travis-ci.org/avagin/criu/jobs/193280324

**Comment by avagin** [comment]
It doesn't work with all patches too.
```
[root@fc24 criu]# python test/zdtm.py run  -t zdtm/static/env00 --remote-lazy-pages -f ns
========================= Run zdtm/static/env00 in ns ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
Run criu page-server
Run criu lazy-pages
Run criu restore
Send the 15 signal to  95
Wait for zdtm/static/env00(95) to die for 0.100000
Wait for zdtm/static/env00(95) to die for 0.200000
Wait for zdtm/static/env00(95) to die for 0.400000
Wait for zdtm/static/env00(95) to die for 0.800000
Wait for zdtm/static/env00(95) to die for 1.600000
Wait for zdtm/static/env00(95) to die for 3.200000
Wait for zdtm/static/env00(95) to die for 6.400000

$ ps axf
 3236 pts/0    S+     0:00              \_ python test/zdtm.py run -t zdtm/static/env00 --remote-lazy-pages
 3246 pts/0    S+     0:00                  \_ ./zdtm_ct zdtm.py
 3247 pts/0    S+     0:00                  |   \_ python2 zdtm.py
 3249 pts/0    S+     0:00                  |       \_ python2 zdtm.py
 3348 ?        Ss     0:00                  |       \_ ../criu/criu page-server -o page-server.log -D dump/zdtm/static/env00/65/1 -v4 --daemon --pidfile ps.pi
 3350 ?        Ss     0:00                  |       \_ ../criu/criu lazy-pages -o lazy-pages.log -D dump/zdtm/static/env00/65/1 -v4 --daemon --pidfile lp.pid 
 3356 ?        Ss     0:00                  |       \_ [env00]
 3367 ?        Ss     0:00                  |           \_ ./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
[root@fc24 criu]# cat /proc/3356/stack 
[<ffffffff912d2efa>] handle_userfault+0x31a/0x670
[<ffffffff91213383>] handle_mm_fault+0x1483/0x15a0
[<ffffffff910510f6>] __do_page_fault+0x266/0x520
[<ffffffff91051488>] trace_do_page_fault+0x58/0x2a0
[<ffffffff9104b24a>] do_async_page_fault+0x1a/0xa0
[<ffffffff917ddc28>] async_page_fault+0x28/0x30
[<ffffffffffffffff>] 0xffffffffffffffff
[root@fc24 criu]# tail  test/dump/zdtm/static/env00/65/1/lazy-pages.log 
(01.523158) lazy-pages: 4-6: uffd_copy: 0x7f15763a8000/4096
(01.523188) polling timeout
(01.523198) pr4-1 Read 7ffc5e54a000 2 pages
(01.523330) lazy-pages: 4-6: uffd_copy: 0x7ffc5e54a000/8192
(01.523362) polling timeout
(01.523403) pr4-1 Read 7ffc5e58b000 2 pages
(01.523707) lazy-pages: 4-6: uffd_copy: 0x7ffc5e58b000/8192
(01.523730) polling timeout
(01.523740) pr1-2 Read 7f157617f000 1 pages
(01.728617) Warn  (criu/page-xfer.c:1143): Unexpected ZERO page received for 0.0
[root@fc24 criu]# tail  test/dump/zdtm/static/env00/65/1/page-server.log 
(00.001438) page-pipe: 		0x7f15763a8000 1
(00.001445) page-pipe: 		0x7ffc5e54a000 2
(00.001453) page-pipe: 		0x7ffc5e58b000 2
(00.001461) page-pipe: 	buf 2 pages, 1 iovs, flags: 0 :
(00.001469) page-pipe: 		0x7ffc5e5f9000 2
(00.001483) page-pipe: * 0 holes:
(00.001492) Starting page server on port 12345
(00.304298) Accepted connection from 127.0.0.1:55272
(00.324513) no iovs found, zero pages
(01.534404) no iovs found, zero pages
```

**Comment by avagin** [comment]
https://github.com/xemul/criu/commit/0f9d1fd4abe5a0118e24c3f7f9a82141b110a0d3
